CREATE DATABASE IF NOT EXISTS blogdb;


USE blogdb;


CREATE TABLE IF NOT EXISTS blogs (

    id INT AUTO_INCREMENT PRIMARY KEY,

    title VARCHAR(255) NOT NULL,

    author VARCHAR(100) NOT NULL,

    description TEXT NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);